### ISSUE TITLE
Modes allowed in I-405 HOV/HOT Lane

### ISSUE THREAD

**Issue by mbshyu** [bellevuewa/BKRCast#53]
Modes allowed on I-405 HOV/HOT lane varies in different year and also different time of day. The current macro for creating the network form the Master Network can correctly get the modes on HOV/HOT lanes for PM and AM periods. An update needs to be done for:
- mid-day modes allowing non-toll HOV2 and toll HOV2 to be free for HOT
- night period allowing all modes to be free for HOT

**Comment by dong-bellevue** [comment]
Fixed. 
It is now HOV2 ride free on I405 at MD and NI. 
7fd1d6f
