### ISSUE TITLE
Bike Model Defaulting to Original EMME_Attr.in file instead of Updated Network Biketype 

### ISSUE THREAD

**Issue by nbleich** [bellevuewa/BKRCast#81]
I am looking at my test runs of the No Project and Project networks that I developed last week, and I noticed something odd. 

How do we update the inputs\bikes\emme_attr.in file? Is there a separate script that needs to be run on the network before running BKRCast to update this file? The date modified on this file in the Inputs folder of all our models is February 28, 2020. It looks like this file isn’t being automatically updated when you run the model on a new network; therefore, it hasn’t captured any of the changes to the bike network. This is also true for our Comp Plan models; the emme_attr.in file is also dated in February 2020. When looking at the attributes in EMME for a future model, the @biketype of a link will be set to “1” but the @bkwt calculation remains unchanged. Here is an example from NE 12th St where the @bkwt the model is using is 10 when the facility is considered “Premium”, and the weight should be 1.

The attributes the bike model uses, @bkfac and @upslp, are only included in the emme_attr.in file. Since these attributes aren’t in EMME as link attributes, does this definition code then default back to the original emme_attr.in file? 
![bike_model](https://user-images.githubusercontent.com/116830892/228085399-9c4ddf14-7ad6-4dfa-819d-1669c5669a6b.png)
![example bike type bike weight error](https://user-images.githubusercontent.com/116830892/228085445-e8a97caa-d123-43dc-9014-112b8a4adc20.png)

**Comment by dong-bellevue** [comment]
`@upslp` is cumulative slope calculated from ArcGIS outside of BKRCast. Values in this attribute do not change so there is no need to update once it is calculated, as long as there is no new link is added to the model.

`@bkfac` is used to calculate bike facility weight, which is then used in bike volume assignment procedure. This attribute is imported together with `@upslp` from an external file named `emme_attr.csv`. After importing, values of `@bkfac` are overwritten by `@biketype`, which includes the latest bike facility type information.
