### ISSUE TITLE
Develop Script to Extract Trips by Binned Distance 

### ISSUE THREAD

**Issue by nbleich** [bellevuewa/BKRCast#82]
A new script is needed to be able to bin trips by distance and select by mode from the Daysim outputs. 

i.e. Short Distance Auto Trips = <1 mile, 1-2 miles, 2-3 miles, 3-5 miles, >5 miles

**Comment by dong-bellevue** [comment]
The requested new feature is added in trip_mode_share_calculator.py. The outputs are saved in trip distance file located in outputs/summary folder.
