### ISSUE TITLE
Load zone partition ga, gb and gt to databank when importing network

### ISSUE THREAD

**Issue by dong-bellevue** [bellevuewa/BKRCast#85]

**Comment by nbleich** [comment]
@dong-bellevue, I was able to test the populate_network2.py and network_importer.py scripts. 

The populate network script isn't exporting the zone partition correctly.  The populate_network2.py script in the Develop branch for the zone partition spec calls for 'ONE_LINE_PER_CATEGORY' but the syntax needs to be updated to 'ONE_ENTRY_PER_LINE'. I tested this on my local machine and with this change and both of the scripts then work correctly. The network_importer.py script is able to read in the zone partitions.

**Comment by dong-bellevue** [comment]
@nbleich I tested it again and I did not see any crash. The partition was correctly exported out and loaded into new network. Maybe you used an old version of populate_network2.py. I updated the file on I drive. Be sure to pull latest BKRCast code before you run the network import. Let me know if what you find.
